const ADMIN = 1
const DSWD = 2
const MAYORSOFFICE = 3
const BUDGET = 4
const TREASURY = 5
const ACCOUNTING = 6
const MANAGER = 7
const MAYOR_AWARDING_CHECK = 8
export default {
  ADMIN: ADMIN,
  DSWD: DSWD,
  MAYORSOFFICE: MAYORSOFFICE,
  BUDGET: BUDGET,
  TREASURY: TREASURY,
  ACCOUNTING: ACCOUNTING,
  MANAGER: MANAGER,
  MAYOR_AWARDING_CHECK: MAYOR_AWARDING_CHECK
}
