const ADMIN = 0
const DSWD = 1
const MAYORSOFFICE = 3
const BUDGET = 4
const TREASURY = 5
const ACCOUNTING = 6
const MANAGER = 7

export default {
  ADMIN: ADMIN,
  DSWD: DSWD,
  MAYORSOFFICE: MAYORSOFFICE,
  BUDGET: BUDGET,
  TREASURY: TREASURY,
  ACCOUNTING: ACCOUNTING,
  MANAGER: MANAGER,
}
